[package]
name = "practice"
version = "0.1.0"
authors = ["Syed Umar Nasar <umarsun786@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libcalc = "0.0.0"